In [636]:
#assess the data and then cleaning the data

In [637]:
import numpy as np
import pandas as pd


In [638]:
df = pd.read_excel('smartphones.xlsx')
df

model    price  rating  \
0                       OnePlus 11 5G  ₹54,999    89.0   
1           OnePlus Nord CE 2 Lite 5G  ₹19,989    81.0   
2               Samsung Galaxy A14 5G  ₹16,499    75.0   
3                Motorola Moto G62 5G  ₹14,999    81.0   
4                  Realme 10 Pro Plus  ₹24,999    82.0   
...                               ...      ...     ...   
1015       Motorola Moto Edge S30 Pro  ₹34,990    83.0   
1016                      Honor X8 5G  ₹14,990    75.0   
1017  POCO X4 GT 5G (8GB RAM + 256GB)  ₹28,990    85.0   
1018             Motorola Moto G91 5G  ₹19,990    80.0   
1019           Samsung Galaxy M52s 5G  ₹24,990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   


In [639]:
#generally your data has 2 kind of problems (any data) 1.Quality related i.e missing data, in accurate data, duplicated data 2. Tidyness issues i.e Data's Structure is wrong like in the sim column above there are plenty of information in single cell which is not correct

In [640]:
# First we do manually assessment, Secondly will do Programetic assesment In both the assessment we write down each and every observations of us.

In [641]:
# after writing all the quality issues, you will have to label issues in 4 categories 1. completeness 2.validity 3.accuracy 4.consistancy 

# Quality Issues
- model - some brands are written diiferently like OPPO in model column -  consistency issue (label)
- price - has unneccesary '₹' - validity
- price - has ',' between numbers - validity
- price - phone Namotel has a price of 99 - accuracy
- ratings - missing values - completeness
- processor - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) - validity
- There is ipod on row 756 - validity
- memory - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) - validity
- battery - incorrect values in - rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) - validity
- display - sometimes frequency is not available - completeness
- display - incorrect values in -  rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) validity
- certain phones are foldable and the info is scattered - validity
- camera - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
camera - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ) -- validity
- card - sometimes contains info about os and camera - validity
- os - sometimes contains info about bluetooth and fm radio - validity
- os - issue with rows (324,378) - validity
- os - sometimes contains os version name like lollipop - consistency
- missing values in camera, card and os - completeness (Camera - 1, Card - 7, os -  17 )
- datatype of price and rating is incorrect - validity


# Tidiness Issues
- sim - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
- ram - can be split into 2 cols RAM and ROM
- processor - can be split into processor name, cores and cpu speed.
- battery - can be split into battery capacity, fast_charging_available
- display - can be split into size, resolution_width, resolution_height and frequency
- camera - can be split into front and rear camera
- card - can be split into supported, extended_upto

In [642]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   model      1020 non-null   object 
 1   price      1020 non-null   object 
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object 
 4   processor  1020 non-null   object 
 5   ram        1020 non-null   object 
 6   battery    1020 non-null   object 
 7   display    1020 non-null   object 
 8   camera     1019 non-null   object 
 9   card       1013 non-null   object 
 10  os         1003 non-null   object 
dtypes: float64(1), object(10)
memory usage: 87.8+ KB


In [643]:
df.describe()

rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [644]:
df.describe(include= 'object')

model    price                             sim  \
count            1020     1020                            1020   
unique           1020      412                              28   
top     OnePlus 11 5G  ₹14,999  Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
freq                1       21                             324   

                                             processor  \
count                                             1020   
unique                                             298   
top     Dimensity 700 5G, Octa Core, 2.2 GHz Processor   
freq                                                29   

                             ram                                  battery  \
count                       1020                                     1020   
unique                        58                                      256   
top     8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 33W Fast Charging   
freq                         267                                      103   

                                                  display  \
count                                                1020   
unique                                                369   
top     6.67 inches, 1080 x 2400 px, 120 Hz Display wi...   
freq                                                   54   

                                                   camera  \
count                                                1019   
unique                                                285   
top     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
freq                                                   40   

                                    card           os  
count                               1013         1003  
unique                                63           48  
top     Memory Card Supported, upto 1 TB  Android v12  
freq                                 171          287

In [645]:
df.duplicated().sum()

0

In [646]:
df.isnull().sum()

model          0
price          0
rating       141
sim            0
processor      0
ram            0
battery        0
display        0
camera         1
card           7
os            17
dtype: int64

In [647]:
df['price']

0       ₹54,999
1       ₹19,989
2       ₹16,499
3       ₹14,999
4       ₹24,999
         ...   
1015    ₹34,990
1016    ₹14,990
1017    ₹28,990
1018    ₹19,990
1019    ₹24,990
Name: price, Length: 1020, dtype: object

In [648]:
#make a copy of dataframe first

df1 = df.copy()
df1

model    price  rating  \
0                       OnePlus 11 5G  ₹54,999    89.0   
1           OnePlus Nord CE 2 Lite 5G  ₹19,989    81.0   
2               Samsung Galaxy A14 5G  ₹16,499    75.0   
3                Motorola Moto G62 5G  ₹14,999    81.0   
4                  Realme 10 Pro Plus  ₹24,999    82.0   
...                               ...      ...     ...   
1015       Motorola Moto Edge S30 Pro  ₹34,990    83.0   
1016                      Honor X8 5G  ₹14,990    75.0   
1017  POCO X4 GT 5G (8GB RAM + 256GB)  ₹28,990    85.0   
1018             Motorola Moto G91 5G  ₹19,990    80.0   
1019           Samsung Galaxy M52s 5G  ₹24,990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   


In [649]:
#removing ₹ and ',' symbols and convert it into the integer datatype
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')


In [650]:
df1

model  price  rating  \
0                       OnePlus 11 5G  54999    89.0   
1           OnePlus Nord CE 2 Lite 5G  19989    81.0   
2               Samsung Galaxy A14 5G  16499    75.0   
3                Motorola Moto G62 5G  14999    81.0   
4                  Realme 10 Pro Plus  24999    82.0   
...                               ...    ...     ...   
1015       Motorola Moto Edge S30 Pro  34990    83.0   
1016                      Honor X8 5G  14990    75.0   
1017  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018             Motorola Moto G91 5G  19990    80.0   
1019           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4     108 MP + 8 MP + 2 

### In the issues which we have mentioned there we have also mentioned the problematic rows with their index numbers
### and these index numbers starts from 2 in the excel where as our dataframe starts from zero so we need to reset the index so that we can find all the problametic rows

In [651]:
df1

model  price  rating  \
0                       OnePlus 11 5G  54999    89.0   
1           OnePlus Nord CE 2 Lite 5G  19989    81.0   
2               Samsung Galaxy A14 5G  16499    75.0   
3                Motorola Moto G62 5G  14999    81.0   
4                  Realme 10 Pro Plus  24999    82.0   
...                               ...    ...     ...   
1015       Motorola Moto Edge S30 Pro  34990    83.0   
1016                      Honor X8 5G  14990    75.0   
1017  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018             Motorola Moto G91 5G  19990    80.0   
1019           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4     108 MP + 8 MP + 2 

In [652]:
df1.reset_index(inplace=True)

In [653]:
df1

index                            model  price  rating  \
0         0                    OnePlus 11 5G  54999    89.0   
1         1        OnePlus Nord CE 2 Lite 5G  19989    81.0   
2         2            Samsung Galaxy A14 5G  16499    75.0   
3         3             Motorola Moto G62 5G  14999    81.0   
4         4               Realme 10 Pro Plus  24999    82.0   
...     ...                              ...    ...     ...   
1015   1015       Motorola Moto Edge S30 Pro  34990    83.0   
1016   1016                      Honor X8 5G  14990    75.0   
1017   1017  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1018             Motorola Moto G91 5G  19990    80.0   
1019   1019           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple

In [654]:
df1['index'] = df1['index']+2

In [655]:
df1

index                            model  price  rating  \
0         2                    OnePlus 11 5G  54999    89.0   
1         3        OnePlus Nord CE 2 Lite 5G  19989    81.0   
2         4            Samsung Galaxy A14 5G  16499    75.0   
3         5             Motorola Moto G62 5G  14999    81.0   
4         6               Realme 10 Pro Plus  24999    82.0   
...     ...                              ...    ...     ...   
1015   1017       Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                      Honor X8 5G  14990    75.0   
1017   1019  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020             Motorola Moto G91 5G  19990    80.0   
1019   1021           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple

In [656]:
# Now we will be copying all the rows of the columns which are having an issue.. and saving those in the variable..

In [657]:
processor_rows  = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))


In [658]:
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))

In [659]:
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))

In [660]:
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))

In [661]:
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016))

In [662]:
#problematic rows

df1[df1['index'].isin (processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

index                              model   price  rating  \
98      100                     Vivo X Fold 5G  106990     NaN   
111     113                    Apple iPhone 12   51999    74.0   
149     151               Apple iPhone 12 Mini   40999    74.0   
155     157                    Nokia 2780 Flip    4990     NaN   
159     161                    Oppo Find N2 5G   94990     NaN   
...     ...                                ...     ...     ...   
954     956  Vivo X Fold 5G (12GB RAM + 512GB)  118990     NaN   
988     990                Nokia 5310 Dual Sim    3399     NaN   
993     995                      Huawei Mate X  169000     NaN   
1000   1002                    XTouch F40 Flip    1999     NaN   
1014   1016                      Vivo X Fold 2  119990     NaN   

                                                    sim  \
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
111             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
155                             Dual Sim, 3G, 4G, Wi-Fi   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
...                                                 ...   
954             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
988                                            Dual Sim   
993   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1000                                           Dual Sim   
1014            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                             processor  \
98       Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
111           Bionic A14, Hexa Core, 3.1 GHz Processor   
149           Bionic A14, Hexa Core, 3.1 GHz Processor   
155     Snapdragon QM215, Quad Core, 1.3 GHz Processor   
159   Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
...                                                ...   
954      Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
988                            8 MB RAM, 16 MB inbuilt   
993          Kirin  990, Octa Core, 2.86 GHz Processor   
1000                                             No 3G   
1014   Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   

                            ram  \
98    12 GB RAM, 256 GB inbuilt   
111     4 GB RAM, 64 GB inbuilt   
149     4 GB RAM, 64 GB inbuilt   
155    4 GB RAM, 512 MB inbuilt   
159   12 GB RAM, 256 GB inbuilt   
...                         ...   
954   12 GB RAM, 512 GB inbuilt   
988            1200 mAh Battery   
993    8 GB RAM, 512 GB inbuilt   
1000                    No Wifi   
1014  12 GB RAM, 256 GB inbuilt   

                                                battery  \
98              4600 mAh Battery with 66W Fast Charging   
111   6.1 inches, 1170 x 2532 px Display with Large ...   
149                  5.4 inches, 1080 x 2340 px Display   
155                                    1450 mAh Battery   
159             4520 mAh Battery with 67W Fast Charging   
...                                                 ...   
954             4600 mAh Battery with 66W Fast Charging   
988                    2.4 inches, 240 x 320 px Display   
993             4500 mAh Battery with 55W Fast Charging   
1000                           32 MB RAM, 32 MB inbuilt   
1014            4800 mAh Battery with 66W Fast Charging   

                                                display  \
98          8.03 inches, 1916 x 2160 px, 120 Hz Display   
111        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
155                    2.7 inches, 240 x 320 px Display   
159   7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
...                                                 ...   
954         8.03 inches, 1916 x 2160 px, 120 Hz Display   
988                                  0.3 MP Rear Camera   
993                    8 inches, 2200 x 2480 px Display   
1000                                    800 mAh Battery   
1014        8.03 inches, 191

In [663]:
# let's find out common rows which are having problems for all the columns

df1[df1['index'].isin (processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]

# you can see there is a shifting issue,,, processor's information is in ram, battery's information is in ram, display's information in battery etc...

index                   model  price  rating  \
640     642          Nokia 105 Plus   1299     NaN   
645     647         Nokia 2760 Flip   5490     NaN   
647     649       Motorola Moto A10   1339     NaN   
657     659           Zanco Tiny T1   2799     NaN   
665     667            itel it2163S    958     NaN   
748     750            Nokia 400 4G   3290     NaN   
757     759            Karbonn KU3i    995     NaN   
817     819            itel Magic X   2239     NaN   
882     884  Nokia 5710 XpressAudio   4799     NaN   
925     927           Nokia 3310 4G   3999     NaN   
927     929      Samsung Guru E1200   1685     NaN   
930     932        iKall K88 Pro 4G   2099     NaN   
1000   1002         XTouch F40 Flip   1999     NaN   

                                 sim                   processor  \
640                         Dual Sim      4 MB RAM, 4 MB inbuilt   
645          Dual Sim, 3G, 4G, Wi-Fi            1450 mAh Battery   
647                         Dual Sim      4 MB RAM, 4 MB inbuilt   
657                       Single Sim    32 MB RAM, 32 MB inbuilt   
665                         Dual Sim      4 MB RAM, 4 MB inbuilt   
748       Dual Sim, 4G, VoLTE, Wi-Fi            2000 mAh Battery   
757                         Dual Sim    52 MB RAM, 32 MB inbuilt   
817   Dual Sim, 3G, 4G, VoLTE, Wi-Fi                       No 3G   
882                 Dual Sim, 3G, 4G                     No Wifi   
925   Dual Sim, 3G, 4G, VoLTE, Wi-Fi  256 MB RAM, 512 MB inbuilt   
927                       Single Sim                     No Wifi   
930          Dual Sim, 3G, 4G, VoLTE   48 MB RAM, 128 MB inbuilt   
1000                        Dual Sim                       No 3G   

                                   ram                            battery  \
640                    800 mAh Battery  1.77 inches, 128 x 160 px Display   
645   3.6 inches, 240 x 320 px Display      5 MP Rear & 5 MP Front Camera   
647                   1750 mAh Battery   1.8 inches, 160 x 128 px Display   
657                    200 mAh Battery    0.49 inches, 64 x 32 px Display   
665                   1200 mAh Battery   1.8 inches, 160 x 128 px Display   
748   2.4 inches, 240 x 320 px Display  0.3 MP Rear & 0.3 MP Front Camera   
757                   1000 mAh Battery   1.8 inches, 128 x 160 px Display   
817                               T117          48 MB RAM, 128 MB inbuilt   
882                        Unisoc T107          48 MB RAM, 128 MB inbuilt   
925                   1200 mAh Battery   2.4 inches, 240 x 320 px Display   
927                    800 mAh Battery   1.5 inches, 128 x 128 px Display   
930                   1800 mAh Battery   2.4 inches, 240 x 360 px Display   
1000                           No Wifi           32 MB RAM, 32 MB inbuilt   

                                display                              camera  \
640                      No Rear Camera   Memory Card Supported, upto 32 GB   
645   Memory Card Supported, upto 32 GB                          Kaios v3.0   
647                      No Rear Camera   Memory Card Supported, upto 32 GB   
657                      No Rear Camera                         No FM Radio   
665                      No Rear Camera   Memory Card Supported, upto 32 GB   
748   Memory Card Supported, upto 64 GB                           Bluetooth   
757                      No Rear Camera   Memory Card Supported, upto 16 GB   
817                    1200 mAh Battery    2.4 inches, 240 x 320 px Display   
882                    1450 mAh Battery    2.4 inches, 240 x 320 px Display   
925                    2 MP Rear Camera   Memory Card Supported, upto 32 GB   
927                      No Rear Camera                         No FM Radio   
930                  0.3 MP Rear Camera  Memory Card Supported, upto 128 GB   
1000                    800 mAh Battery   1.77 inches, 240 x 320 px Display   

                    card                                 os  
640            Bluetooth                        

In [664]:
df1[df1['index'].isin (processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]['price']
df1[df1['index'].isin (processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]['price'].mean()
# if you check the price of above problamatic rows then you can see that those are very low cost phones, seems not smartphones at all, those are keypad phones. 

2537.6923076923076

In [665]:
# So now we will remove these phones which are not smartphones. 

# We are considering that if the phone is above the price of 3400 INR then its a smartphone else keypad phones so here is what we will extract




df1 = df1[df1['price']>=3400]
df1.sample(5)




index                       model  price  rating  \
1015   1017  Motorola Moto Edge S30 Pro  34990    83.0   
114     116             Xiaomi Redmi A1   6171     NaN   
507     509        Xiaomi Redmi A1 Plus   7289    60.0   
151     153           Motorola Moto G52  11999    75.0   
529     531          Samsung Galaxy F14  14990    67.0   

                                      sim  \
1015   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
114        Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
507        Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
151   Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC   
529   Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC   

                                          processor                       ram  \
1015  Snapdragon 8 Gen1, Octa Core, 3 GHz Processor  8 GB RAM, 128 GB inbuilt   
114           Helio A22, Quad Core, 2 GHz Processor   2 GB RAM, 32 GB inbuilt   
507           Helio A22, Quad Core, 2 GHz Processor   2 GB RAM, 32 GB inbuilt   
151    Snapdragon 680, Octa Core, 2.4 GHz Processor   4 GB RAM, 64 GB inbuilt   
529                             Octa Core Processor   4 GB RAM, 64 GB inbuilt   

                                        battery  \
1015  5000 mAh Battery with 68.2W Fast Charging   
114     5000 mAh Battery with 10W Fast Charging   
507     5000 mAh Battery with 10W Fast Charging   
151     5000 mAh Battery with 33W Fast Charging   
529     5000 mAh Battery with 25W Fast Charging   

                                                display  \
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
114   6.52 inches, 720 x 1600 px Display with Water ...   
507   6.52 inches, 720 x 1600 px Display with Water ...   
151   6.6 inches, 2460 x 1080 px, 90 Hz Display with...   
529   6.62 inches, 2408 x 1080 px Display with Punch...   

                                                 camera  \
1015  64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
114                  8 MP Dual Rear & 5 MP Front Camera   
507         8 MP + 0.3 MP Dual Rear & 5 MP Front Camera   
151   50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
529   50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...   

                                    card           os  
1015                         Android v12  No FM Radio  
114   Memory Card Supported, upto 512 GB  Android v12  
507   Memory Card Supported, upto 512 GB  Android v12  
151                 Memory Card (Hybrid)  Android v12  
529     Memory Card Supported, upto 1 TB  Android v13

In [666]:
df1

index                            model  price  rating  \
0         2                    OnePlus 11 5G  54999    89.0   
1         3        OnePlus Nord CE 2 Lite 5G  19989    81.0   
2         4            Samsung Galaxy A14 5G  16499    75.0   
3         5             Motorola Moto G62 5G  14999    81.0   
4         6               Realme 10 Pro Plus  24999    82.0   
...     ...                              ...    ...     ...   
1015   1017       Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                      Honor X8 5G  14990    75.0   
1017   1019  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020             Motorola Moto G91 5G  19990    80.0   
1019   1021           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple

In [667]:
#Let's analyse the processor column now

df1[df1['index'].isin(processor_rows)]

# all the followings looks like feature phones and we are dropping these...

index                   model  price  rating  \
645    647         Nokia 2760 Flip   5490     NaN   
857    859             LG Folder 2  11999     NaN   
882    884  Nokia 5710 XpressAudio   4799     NaN   
925    927           Nokia 3310 4G   3999     NaN   

                                sim                   processor  \
645         Dual Sim, 3G, 4G, Wi-Fi            1450 mAh Battery   
857       Single Sim, 3G, 4G, Wi-Fi      1 GB RAM, 8 GB inbuilt   
882                Dual Sim, 3G, 4G                     No Wifi   
925  Dual Sim, 3G, 4G, VoLTE, Wi-Fi  256 MB RAM, 512 MB inbuilt   

                                  ram                           battery  \
645  3.6 inches, 240 x 320 px Display     5 MP Rear & 5 MP Front Camera   
857                  1470 mAh Battery  2.8 inches, 240 x 320 px Display   
882                       Unisoc T107         48 MB RAM, 128 MB inbuilt   
925                  1200 mAh Battery  2.4 inches, 240 x 320 px Display   

                               display                             camera  \
645  Memory Card Supported, upto 32 GB                         Kaios v3.0   
857                   2 MP Rear Camera              Memory Card Supported   
882                   1450 mAh Battery   2.4 inches, 240 x 320 px Display   
925                   2 MP Rear Camera  Memory Card Supported, upto 32 GB   

                   card                                 os  
645           Bluetooth                                NaN  
857           Bluetooth                                NaN  
882  0.3 MP Rear Camera  Memory Card Supported, upto 32 GB  
925           Bluetooth                            Browser

In [668]:
df1.drop([645,857,882,925],inplace=True)

/var/folders/nb/094jxb115nj0gjxwpmy6b2cc0000gn/T/ipykernel_29461/1676279141.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([645,857,882,925],inplace=True)


In [669]:
df1[df1['index'].isin(processor_rows)]

Empty DataFrame
Columns: [index, model, price, rating, sim, processor, ram, battery, display, camera, card, os]
Index: []

In [670]:
df1[df1['index'].isin(ram_rows)]

# We are removing 582th row as it seems normal feature phone not a smart phone

index                             model   price  rating  \
439    441            Apple iPhone SE 3 2022   43900     NaN   
483    485  Huawei Mate 50 RS Porsche Design  239999    81.0   
582    584                     Nokia 8210 4G    3749     NaN   

                                                 sim  \
439          Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
483  Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster   
582                                 Dual Sim, 3G, 4G   

                                            processor             ram  \
439        Bionic  A15, Hexa Core, 3.22 GHz Processor   64 GB inbuilt   
483  Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor  512 GB inbuilt   
582                                           No Wifi     Unisoc T107   

                                     battery  \
439        4.7 inches, 750 x 1334 px Display   
483  4700 mAh Battery with 66W Fast Charging   
582                48 MB RAM, 128 MB inbuilt   

                                         display  \
439               12 MP Rear & 7 MP Front Camera   
483  6.74 inches, 1212 x 2616 px, 120 Hz Display   
582                             1450 mAh Battery   

                                                camera  \
439                          Memory Card Not Supported   
483  50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...   
582                   2.8 inches, 240 x 320 px Display   

                                  card                                 os  
439                            iOS v15                        No FM Radio  
483  Memory Card (Hybrid), upto 256 GB                   Hongmeng OS v3.0  
582                 0.3 MP Rear Camera  Memory Card Supported, upto 32 GB

In [671]:
df1.drop(582,inplace=True)

/var/folders/nb/094jxb115nj0gjxwpmy6b2cc0000gn/T/ipykernel_29461/544825702.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(582,inplace=True)


In [672]:
df1[df1['index'].isin(battery_rows)]

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
376    378               Nokia 2660 Flip    4649     NaN   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
754    756    Apple iPod Touch (7th Gen)   18900     NaN   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
376                         Dual Sim, 3G, 4G   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
754                                    Wi-Fi   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   
307    Bionic A14, Hexa Core, 3.1 GHz Processor   
363    Bionic A14, Hexa Core, 3.1 GHz Processor   
376                                     No Wifi   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor   
448                                 Bionic  A16   
628    Bionic A14, Hexa Core, 3.1 GHz Processor   
754                               32 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor   
853    Bionic A14, Hexa Core, 3.1 GHz Processor   
913    Bionic A14, Hexa Core, 3.1 GHz Processor   
914    Bionic A14, Hexa Core, 3.1 GHz Processor   

                                 ram  \
111          4 GB RAM, 64 GB inbuilt   
149          4 GB RAM, 64 GB inbuilt   
307         4 GB RAM, 128 GB inbuilt   
363         4 GB RAM, 128 GB inbuilt   
376                      Unisoc T107   
439                    64 GB inbuilt   
448         8 GB RAM, 128 GB inbuilt   
628         6 GB RAM, 512 GB inbuilt   
754  4 inches, 640 x 1136 px Display   
762                    64 GB inbuilt   
853         6 GB RAM, 256 GB inbuilt   
913         4 GB RAM, 256 GB inbuilt   
914         4 GB RAM, 256 GB inbuilt   

                                               battery  \
111  6.1 inches, 1170 x 2532 px Display with Large ...   
149                 5.4 inches, 1080 x 2340 px Display   
307  6.1 inches, 1170 x 2532 px Display with Large ...   
363                 5.4 inches, 1080 x 2340 px Display   
376                          48 MB RAM, 128 MB inbuilt   
439                  4.7 inches, 750 x 1334 px Display   
448  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628  6.1 inches, 1170 x 2532 px Display with Large ...   
754                    8 MP Rear & 1.2 MP Front Camera   
762                  6.1 inches, 750 x 1580 px Display   
853  6.1 inches, 1170 x 2532 px Display with Large ...   
913                 5.4 inches, 1080 x 2340 px Display   
914  6.1 inches, 1170 x 2532 px Display with Large ...   

                                               display  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
376                                   1450 mAh Battery   
439                     12 MP Rear & 7 MP Front Camera

In [673]:
# droping one feature phone and one ipod 

In [674]:
df1.drop([376,754],inplace= True)

/var/folders/nb/094jxb115nj0gjxwpmy6b2cc0000gn/T/ipykernel_29461/4134148675.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([376,754],inplace= True)


In [675]:
df1[df1['index'].isin(battery_rows)]

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

                                               battery  \
111  6.1 inches, 1170 x 2532 px Display with Large ...   
149                 5.4 inches, 1080 x 2340 px Display   
307  6.1 inches, 1170 x 2532 px Display with Large ...   
363                 5.4 inches, 1080 x 2340 px Display   
439                  4.7 inches, 750 x 1334 px Display   
448  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628  6.1 inches, 1170 x 2532 px Display with Large ...   
762                  6.1 inches, 750 x 1580 px Display   
853  6.1 inches, 1170 x 2532 px Display with Large ...   
913                 5.4 inches, 1080 x 2340 px Display   
914  6.1 inches, 1170 x 2532 px Display with Large ...   

                                               display  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439                     12 MP Rear & 7 MP Front Camera   
448  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762                  12 MP Rear & 10.8 MP Front Camera   
853  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
913       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                        camera       card           os  
111  Memory Card Not Supported    iOS v14  No FM Radio  
149  Memory Card Not Supported    iOS v14  No FM Radio  
307  Memory Card Not Supported    iOS v14  No FM Radio  
363  Memory Card Not Supported    iOS v14  No FM Radio  
439  Memory Card Not Supported    iOS v15  No FM Radio  
448  Memory Card Not Supported    iOS v15  No 

In [676]:
# You can see the shifting issues with the apple phones, battery information will get shifted to display and display to camera etc and for that
# we will be using shift function 

In [677]:
temp_df = df1[df1['index'].isin(battery_rows)]

In [678]:
#shifting the rows by 1
temp_df.iloc[:,7:] = temp_df.iloc[:,7:].shift(1,axis=1)
temp_df

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

    battery                                            display  \
111    None  6.1 inches, 1170 x 2532 px Display with Large ...   
149    None                 5.4 inches, 1080 x 2340 px Display   
307    None  6.1 inches, 1170 x 2532 px Display with Large ...   
363    None                 5.4 inches, 1080 x 2340 px Display   
439    None                  4.7 inches, 750 x 1334 px Display   
448    None  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628    None  6.1 inches, 1170 x 2532 px Display with Large ...   
762    None                  6.1 inches, 750 x 1580 px Display   
853    None  6.1 inches, 1170 x 2532 px Display with Large ...   
913    None                 5.4 inches, 1080 x 2340 px Display   
914    None  6.1 inches, 1170 x 2532 px Display with Large ...   

                                                camera  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439                     12 MP Rear & 7 MP Front Camera   
448  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762                  12 MP Rear & 10.8 MP Front Camera   
853  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
913       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                          card         os  
111  Memory Card Not Supported    iOS v14  
149  Memory Card Not Supported    iOS v14  
307  Memory Card Not Supported    iOS v14  
363  Memory Card Not Supported    iOS v14  
439  Memory Card Not Supported    iOS v15  
448  Memory Card Not Support

111	113	Apple iPhone 12	51999	74.0	Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC	Bionic A14, Hexa Core, 3.1 GHz Processor	4 GB RAM, 64 GB inbuilt	6.1 inches, 1170 x 2532 px Display with Large ...	12 MP + 12 MP Dual Rear & 12 MP Front Camera	Memory Card Not Supported	iOS v14	No FM Radio

In [679]:
df1.update(temp_df,na=True)
df1

TypeError: DataFrame.update() got an unexpected keyword argument 'na'

In [ ]:
df1[df1['index'].isin(battery_rows)]

In [680]:
temp_df = df1[df1['index'].isin(battery_rows)]
temp_df

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

                                               battery  \
111  6.1 inches, 1170 x 2532 px Display with Large ...   
149                 5.4 inches, 1080 x 2340 px Display   
307  6.1 inches, 1170 x 2532 px Display with Large ...   
363                 5.4 inches, 1080 x 2340 px Display   
439                  4.7 inches, 750 x 1334 px Display   
448  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628  6.1 inches, 1170 x 2532 px Display with Large ...   
762                  6.1 inches, 750 x 1580 px Display   
853  6.1 inches, 1170 x 2532 px Display with Large ...   
913                 5.4 inches, 1080 x 2340 px Display   
914  6.1 inches, 1170 x 2532 px Display with Large ...   

                                               display  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439                     12 MP Rear & 7 MP Front Camera   
448  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762                  12 MP Rear & 10.8 MP Front Camera   
853  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
913       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                        camera       card           os  
111  Memory Card Not Supported    iOS v14  No FM Radio  
149  Memory Card Not Supported    iOS v14  No FM Radio  
307  Memory Card Not Supported    iOS v14  No FM Radio  
363  Memory Card Not Supported    iOS v14  No FM Radio  
439  Memory Card Not Supported    iOS v15  No FM Radio  
448  Memory Card Not Supported    iOS v15  No 

In [681]:
temp_df

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
111    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149    Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

                                               battery  \
111  6.1 inches, 1170 x 2532 px Display with Large ...   
149                 5.4 inches, 1080 x 2340 px Display   
307  6.1 inches, 1170 x 2532 px Display with Large ...   
363                 5.4 inches, 1080 x 2340 px Display   
439                  4.7 inches, 750 x 1334 px Display   
448  6.06 inches, 1170 x 2532 px, 120 Hz Display wi...   
628  6.1 inches, 1170 x 2532 px Display with Large ...   
762                  6.1 inches, 750 x 1580 px Display   
853  6.1 inches, 1170 x 2532 px Display with Large ...   
913                 5.4 inches, 1080 x 2340 px Display   
914  6.1 inches, 1170 x 2532 px Display with Large ...   

                                               display  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439                     12 MP Rear & 7 MP Front Camera   
448  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762                  12 MP Rear & 10.8 MP Front Camera   
853  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
913       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                        camera       card           os  
111  Memory Card Not Supported    iOS v14  No FM Radio  
149  Memory Card Not Supported    iOS v14  No FM Radio  
307  Memory Card Not Supported    iOS v14  No FM Radio  
363  Memory Card Not Supported    iOS v14  No FM Radio  
439  Memory Card Not Supported    iOS v15  No FM Radio  
448  Memory Card Not Supported    iOS v15  No 

In [682]:
df1.tail(100)

index                                      model  price  rating  \
913     915               Apple iPhone 12 Mini (256GB)  55999    75.0   
914     916                    Apple iPhone 12 (256GB)  67999    76.0   
915     917                                   OPPO A15   9999    66.0   
916     918  Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB)  14439    77.0   
918     920                                   Oppo A12   9990    64.0   
...     ...                                        ...    ...     ...   
1015   1017                 Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                                Honor X8 5G  14990    75.0   
1017   1019            POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020                       Motorola Moto G91 5G  19990    80.0   
1019   1021                     Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
913             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
915                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
916          Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster   
918                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                           processor  \
913         Bionic A14, Hexa Core, 3.1 GHz Processor   
914         Bionic A14, Hexa Core, 3.1 GHz Processor   
915          Helio P35, Octa Core, 2.3 GHz Processor   
916    Snapdragon 720G, Octa Core, 2.3 GHz Processor   
918          Helio P35, Octa Core, 1.8 GHz Processor   
...                                              ...   
1015   Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016  Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017   Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018    Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                             Octa Core Processor   

                           ram  \
913   4 GB RAM, 256 GB inbuilt   
914   4 GB RAM, 256 GB inbuilt   
915    3 GB RAM, 32 GB inbuilt   
916   4 GB RAM, 128 GB inbuilt   
918    3 GB RAM, 32 GB inbuilt   
...                        ...   
1015  8 GB RAM, 128 GB inbuilt   
1016  6 GB RAM, 128 GB inbuilt   
1017  8 GB RAM, 256 GB inbuilt   
1018  6 GB RAM, 128 GB inbuilt   
1019  8 GB RAM, 128 GB inbuilt   

                                                battery  \
913                  5.4 inches, 1080 x 2340 px Display   
914   6.1 inches, 1170 x 2532 px Display with Large ...   
915                                    4230 mAh Battery   
916             5020 mAh Battery with 18W Fast Charging   
918                                    4230 mAh Battery   
...                                                 ...   
1015          5000 mAh Battery with 68.2W Fast Charging   
1016          5000 mAh Battery with 22.5W Fast Charging   
1017            5080 mAh Battery with 67W Fast Charging   
1018                5000 mAh Battery with Fast Charging   
1019                5000 mAh Battery with Fast Charging   

                                                display  \
913        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
915   6.52 inches, 720 x 1600 px Display with Water ...   
916   6.67 inches, 1080 x 2400 px Display with Punch...   
918   6.22 inches, 1520 x 720 px Display with Water ...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Displa

In [683]:
df1.tail(100)

index                                      model  price  rating  \
913     915               Apple iPhone 12 Mini (256GB)  55999    75.0   
914     916                    Apple iPhone 12 (256GB)  67999    76.0   
915     917                                   OPPO A15   9999    66.0   
916     918  Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB)  14439    77.0   
918     920                                   Oppo A12   9990    64.0   
...     ...                                        ...    ...     ...   
1015   1017                 Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                                Honor X8 5G  14990    75.0   
1017   1019            POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020                       Motorola Moto G91 5G  19990    80.0   
1019   1021                     Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
913             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
915                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
916          Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster   
918                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                           processor  \
913         Bionic A14, Hexa Core, 3.1 GHz Processor   
914         Bionic A14, Hexa Core, 3.1 GHz Processor   
915          Helio P35, Octa Core, 2.3 GHz Processor   
916    Snapdragon 720G, Octa Core, 2.3 GHz Processor   
918          Helio P35, Octa Core, 1.8 GHz Processor   
...                                              ...   
1015   Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016  Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017   Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018    Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                             Octa Core Processor   

                           ram  \
913   4 GB RAM, 256 GB inbuilt   
914   4 GB RAM, 256 GB inbuilt   
915    3 GB RAM, 32 GB inbuilt   
916   4 GB RAM, 128 GB inbuilt   
918    3 GB RAM, 32 GB inbuilt   
...                        ...   
1015  8 GB RAM, 128 GB inbuilt   
1016  6 GB RAM, 128 GB inbuilt   
1017  8 GB RAM, 256 GB inbuilt   
1018  6 GB RAM, 128 GB inbuilt   
1019  8 GB RAM, 128 GB inbuilt   

                                                battery  \
913                  5.4 inches, 1080 x 2340 px Display   
914   6.1 inches, 1170 x 2532 px Display with Large ...   
915                                    4230 mAh Battery   
916             5020 mAh Battery with 18W Fast Charging   
918                                    4230 mAh Battery   
...                                                 ...   
1015          5000 mAh Battery with 68.2W Fast Charging   
1016          5000 mAh Battery with 22.5W Fast Charging   
1017            5080 mAh Battery with 67W Fast Charging   
1018                5000 mAh Battery with Fast Charging   
1019                5000 mAh Battery with Fast Charging   

                                                display  \
913        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
915   6.52 inches, 720 x 1600 px Display with Water ...   
916   6.67 inches, 1080 x 2400 px Display with Punch...   
918   6.22 inches, 1520 x 720 px Display with Water ...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Displa

In [684]:


df1.loc[df1['index'].isin(temp_df['index']), 'battery'] = np.nan
df1

index                            model  price  rating  \
0         2                    OnePlus 11 5G  54999    89.0   
1         3        OnePlus Nord CE 2 Lite 5G  19989    81.0   
2         4            Samsung Galaxy A14 5G  16499    75.0   
3         5             Motorola Moto G62 5G  14999    81.0   
4         6               Realme 10 Pro Plus  24999    82.0   
...     ...                              ...    ...     ...   
1015   1017       Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                      Honor X8 5G  14990    75.0   
1017   1019  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020             Motorola Moto G91 5G  19990    80.0   
1019   1021           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple

In [685]:
df1[df1['index'].isin(temp_df['index'])]['battery'] 

111    NaN
149    NaN
307    NaN
363    NaN
439    NaN
448    NaN
628    NaN
762    NaN
853    NaN
913    NaN
914    NaN
Name: battery, dtype: object

In [686]:
df1.tail(100)


index                                      model  price  rating  \
913     915               Apple iPhone 12 Mini (256GB)  55999    75.0   
914     916                    Apple iPhone 12 (256GB)  67999    76.0   
915     917                                   OPPO A15   9999    66.0   
916     918  Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB)  14439    77.0   
918     920                                   Oppo A12   9990    64.0   
...     ...                                        ...    ...     ...   
1015   1017                 Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                                Honor X8 5G  14990    75.0   
1017   1019            POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020                       Motorola Moto G91 5G  19990    80.0   
1019   1021                     Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
913             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
915                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
916          Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster   
918                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                           processor  \
913         Bionic A14, Hexa Core, 3.1 GHz Processor   
914         Bionic A14, Hexa Core, 3.1 GHz Processor   
915          Helio P35, Octa Core, 2.3 GHz Processor   
916    Snapdragon 720G, Octa Core, 2.3 GHz Processor   
918          Helio P35, Octa Core, 1.8 GHz Processor   
...                                              ...   
1015   Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016  Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017   Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018    Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                             Octa Core Processor   

                           ram                                    battery  \
913   4 GB RAM, 256 GB inbuilt                                        NaN   
914   4 GB RAM, 256 GB inbuilt                                        NaN   
915    3 GB RAM, 32 GB inbuilt                           4230 mAh Battery   
916   4 GB RAM, 128 GB inbuilt    5020 mAh Battery with 18W Fast Charging   
918    3 GB RAM, 32 GB inbuilt                           4230 mAh Battery   
...                        ...                                        ...   
1015  8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016  6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017  8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018  6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019  8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
913        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914        12 MP + 12 MP Dual Rear & 12 MP Front Camera   
915   6.52 inches, 720 x 1600 px Display with Water ...   
916   6.67 inches, 1080 x 2400 px Display with Punch...   
918   6.22 inches, 1520 x 720 px Display with Water ...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
913                           Memory Card Not Supporte

In [687]:
#display rows

df1[df1['index'].isin(display_rows)]

index                         model   price  rating  \
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
762    764             Apple iPhone SE 4   49990    60.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                      processor                       ram  \
439  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                 Bionic  A16  8 GB RAM, 128 GB inbuilt   
628    Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
762  Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
913    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914    Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

    battery                                            display  \
439     NaN                     12 MP Rear & 7 MP Front Camera   
448     NaN  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
628     NaN  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
762     NaN                  12 MP Rear & 10.8 MP Front Camera   
913     NaN       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
914     NaN       12 MP + 12 MP Dual Rear & 12 MP Front Camera   

                        camera       card           os  
439  Memory Card Not Supported    iOS v15  No FM Radio  
448  Memory Card Not Supported    iOS v15  No FM Radio  
628  Memory Card Not Supported  iOS v14.0  No FM Radio  
762  Memory Card Not Supported    iOS v16  No FM Radio  
913  Memory Card Not Supported    iOS v14  No FM Radio  
914  Memory Card Not Supported    iOS v14  No FM Radio

In [688]:
# camera rows


df1[df1['index'].isin(camera_rows)]

#155,271 is a feature phone so we will drop it

df1.drop([155,271],inplace = True)


/var/folders/nb/094jxb115nj0gjxwpmy6b2cc0000gn/T/ipykernel_29461/584747411.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([155,271],inplace = True)


In [689]:
df

model    price  rating  \
0                       OnePlus 11 5G  ₹54,999    89.0   
1           OnePlus Nord CE 2 Lite 5G  ₹19,989    81.0   
2               Samsung Galaxy A14 5G  ₹16,499    75.0   
3                Motorola Moto G62 5G  ₹14,999    81.0   
4                  Realme 10 Pro Plus  ₹24,999    82.0   
...                               ...      ...     ...   
1015       Motorola Moto Edge S30 Pro  ₹34,990    83.0   
1016                      Honor X8 5G  ₹14,990    75.0   
1017  POCO X4 GT 5G (8GB RAM + 256GB)  ₹28,990    85.0   
1018             Motorola Moto G91 5G  ₹19,990    80.0   
1019           Samsung Galaxy M52s 5G  ₹24,990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3     50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   


In [690]:
temp_df = df1[df1['index'].isin(camera_rows)]
temp_df

index                                     model   price  rating  \
98      100                            Vivo X Fold 5G  106990     NaN   
111     113                           Apple iPhone 12   51999    74.0   
149     151                      Apple iPhone 12 Mini   40999    74.0   
159     161                           Oppo Find N2 5G   94990     NaN   
236     238                      Xiaomi Mix Fold 2 5G  106990     NaN   
306     308                   Samsung Galaxy Z Flip 3   69999    84.0   
307     309                   Apple iPhone 12 (128GB)   55999    75.0   
321     323                   Samsung Galaxy Z Fold 4  154998     NaN   
322     324                          Royole FlexPai 2  109999    87.0   
363     365              Apple iPhone 12 Mini (128GB)   45999    75.0   
365     367                          OPPO Find N Flip   89990    88.0   
392     394                         OPPO Find N2 Flip   70990    88.0   
439     441                    Apple iPhone SE 3 2022   43900     NaN   
448     450                       Apple iPhone 15 Pro  130990    75.0   
482     484                          Vivo X Fold Plus  113990     NaN   
504     506                Samsung Galaxy Z Flip 4 5G   89999    88.0   
569     571                   Samsung Galaxy Z Fold 3  110999    89.0   
570     572                                LG Wing 5G   54999    89.0   
613     615                              Oukitel WP21   22990    82.0   
628     630               Apple iPhone 12 Pro (512GB)  139900    80.0   
682     684                              LG V60 ThinQ   79990     NaN   
703     705                            Oppo Find N 5G   92249     NaN   
709     711                               OPPO X 2021  134999    86.0   
721     723                Asus ROG Phone 6D Ultimate  107990     NaN   
726     728                          Huawei Mate Xs 2  162990    89.0   
762     764                         Apple iPhone SE 4   49990    60.0   
790     792                        Xiaomi Mi Mix Fold  109990     NaN   
844     846                              CAT S22 Flip   14999     NaN   
853     855               Apple iPhone 12 Pro (256GB)  119900    80.0   
856     858                   Samsung Galaxy A01 Core    4999     NaN   
894     896                       Royole FlexPai 3 5G  149999    87.0   
913     915              Apple iPhone 12 Mini (256GB)   55999    75.0   
914     916                   Apple iPhone 12 (256GB)   67999    76.0   
943     945  Samsung Galaxy Z Fold 4 (12GB RAM + 1TB)  163980     NaN   
954     956         Vivo X Fold 5G (12GB RAM + 512GB)  118990     NaN   
993     995                             Huawei Mate X  169000     NaN   
1014   1016                             Vivo X Fold 2  119990     NaN   

                                                    sim  \
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
111             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
306           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
321             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
322                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
363             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
365           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
392           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
482             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
504             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
569             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
570             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
613                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
628             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi,

In [691]:
#finding the string mp in the camera column so that we can find the other rows which does not have MP and have issues and written like
# foldable etc..
#not that we have added not symbol below so that we can get all the rows other than which has the string 'MP'
#all these below phones are foldable display etc..
temp_df = temp_df[~temp_df['camera'].str.contains('MP')] 



In [692]:
# now we have to put all the card rows in the camera for the above mentioned dataset... 

In [693]:
df1.loc[temp_df.index,'camera'] =  temp_df['card'].values

In [694]:
df1[df1['index'].isin(camera_rows)]

index                                     model   price  rating  \
98      100                            Vivo X Fold 5G  106990     NaN   
111     113                           Apple iPhone 12   51999    74.0   
149     151                      Apple iPhone 12 Mini   40999    74.0   
159     161                           Oppo Find N2 5G   94990     NaN   
236     238                      Xiaomi Mix Fold 2 5G  106990     NaN   
306     308                   Samsung Galaxy Z Flip 3   69999    84.0   
307     309                   Apple iPhone 12 (128GB)   55999    75.0   
321     323                   Samsung Galaxy Z Fold 4  154998     NaN   
322     324                          Royole FlexPai 2  109999    87.0   
363     365              Apple iPhone 12 Mini (128GB)   45999    75.0   
365     367                          OPPO Find N Flip   89990    88.0   
392     394                         OPPO Find N2 Flip   70990    88.0   
439     441                    Apple iPhone SE 3 2022   43900     NaN   
448     450                       Apple iPhone 15 Pro  130990    75.0   
482     484                          Vivo X Fold Plus  113990     NaN   
504     506                Samsung Galaxy Z Flip 4 5G   89999    88.0   
569     571                   Samsung Galaxy Z Fold 3  110999    89.0   
570     572                                LG Wing 5G   54999    89.0   
613     615                              Oukitel WP21   22990    82.0   
628     630               Apple iPhone 12 Pro (512GB)  139900    80.0   
682     684                              LG V60 ThinQ   79990     NaN   
703     705                            Oppo Find N 5G   92249     NaN   
709     711                               OPPO X 2021  134999    86.0   
721     723                Asus ROG Phone 6D Ultimate  107990     NaN   
726     728                          Huawei Mate Xs 2  162990    89.0   
762     764                         Apple iPhone SE 4   49990    60.0   
790     792                        Xiaomi Mi Mix Fold  109990     NaN   
844     846                              CAT S22 Flip   14999     NaN   
853     855               Apple iPhone 12 Pro (256GB)  119900    80.0   
856     858                   Samsung Galaxy A01 Core    4999     NaN   
894     896                       Royole FlexPai 3 5G  149999    87.0   
913     915              Apple iPhone 12 Mini (256GB)   55999    75.0   
914     916                   Apple iPhone 12 (256GB)   67999    76.0   
943     945  Samsung Galaxy Z Fold 4 (12GB RAM + 1TB)  163980     NaN   
954     956         Vivo X Fold 5G (12GB RAM + 512GB)  118990     NaN   
993     995                             Huawei Mate X  169000     NaN   
1014   1016                             Vivo X Fold 2  119990     NaN   

                                                    sim  \
98              Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
111             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
159             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
236   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
306           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
321             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
322                  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
363             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
365           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
392           Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
482             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
504             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
569             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
570             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
613                      Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
628             Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi,

In [695]:
df1.head(100)

index                      model   price  rating  \
0       2              OnePlus 11 5G   54999    89.0   
1       3  OnePlus Nord CE 2 Lite 5G   19989    81.0   
2       4      Samsung Galaxy A14 5G   16499    75.0   
3       5       Motorola Moto G62 5G   14999    81.0   
4       6         Realme 10 Pro Plus   24999    82.0   
..    ...                        ...     ...     ...   
95     97                  Realme 9i   12499    75.0   
96     98                   OPPO A17   12499    72.0   
97     99                 iQOO 11 5G   59999    88.0   
98    100             Vivo X Fold 5G  106990     NaN   
99    101                 Vivo T1 5G   15990    78.0   

                                        sim  \
0   Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1        Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2        Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3        Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4        Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
..                                      ...   
95           Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
96           Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
97  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
98  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
99       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                          processor  \
0   Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1      Snapdragon 695, Octa Core, 2.2 GHz Processor   
2         Exynos 1330, Octa Core, 2.4 GHz Processor   
3     Snapdragon  695, Octa Core, 2.2 GHz Processor   
4      Dimensity 1080, Octa Core, 2.6 GHz Processor   
..                                              ...   
95    Snapdragon  680, Octa Core, 2.4 GHz Processor   
96          Helio G35, Octa Core, 2.3 GHz Processor   
97  Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
98    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
99    Snapdragon  695, Octa Core, 2.2 GHz Processor   

                          ram                                   battery  \
0   12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   
1    6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
2     4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 15W Fast Charging   
3    6 GB RAM, 128 GB inbuilt       5000 mAh Battery with Fast Charging   
4    6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 67W Fast Charging   
..                        ...                                       ...   
95    4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
96    4 GB RAM, 64 GB inbuilt       5000 mAh Battery with Fast Charging   
97   8 GB RAM, 256 GB inbuilt  5000 mAh Battery with 120W Fast Charging   
98  12 GB RAM, 256 GB inbuilt   4600 mAh Battery with 66W Fast Charging   
99   4 GB RAM, 128 GB inbuilt   5000 mAh Battery with 18W Fast Charging   

                                              display  \
0   6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1   6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2   6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3   6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4   6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
..                                                ...   
95  6.6 inches, 1080 x 2412 px, 90 Hz Display with...   
96  6.56 inches, 720 x 1612 px Display with Water ...   
97  6.78 inches, 1440 x 3200 px, 144 Hz Display wi...   
98        8.03 inches, 1916 x 2160 px, 120 Hz Display   
99  6.58 inches, 1080 x 2408 px, 120 Hz Display wi...   

                                               camera  \
0   50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1   64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2   50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3   50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4   108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   
..                                                ...   
95  50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
96         50 MP + 2 MP Dual Rear & 5 MP Front Camera   
97  50

In [696]:
# card column

In [697]:
df1['card'].value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              112
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         91
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Memory Card (Hybrid), upto 512 GB                                       11
Android v10                                                             11
Memory Card Supporte

In [698]:
# There are plenty of camera information in the card

temp_df =df1[df1['card'].str.contains('MP')]

In [699]:

# finding the card string in the os and replace that in the card column
card_mask = df1['os'].str.contains('card',case = False, na = False)
df1.loc[card_mask,'card'] = df1.loc[card_mask,'os'] 
df1.loc[card_mask,'os'] = None

In [700]:
df1.head(160)

index                      model  price  rating  \
0        2              OnePlus 11 5G  54999    89.0   
1        3  OnePlus Nord CE 2 Lite 5G  19989    81.0   
2        4      Samsung Galaxy A14 5G  16499    75.0   
3        5       Motorola Moto G62 5G  14999    81.0   
4        6         Realme 10 Pro Plus  24999    82.0   
..     ...                        ...    ...     ...   
156    158                 Realme C30   5299     NaN   
157    159            OPPO F21 Pro 5G  25969    82.0   
158    160              Realme 11 Pro  28999    82.0   
159    161            Oppo Find N2 5G  94990     NaN   
160    162                Realme 9 4G  14999    81.0   

                                         sim  \
0    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4         Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
..                                       ...   
156           Dual Sim, 3G, 4G, VoLTE, Wi-Fi   
157       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
158       Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
159  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
160           Dual Sim, 3G, 4G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
..                                                ...   
156         Tiger T612, Octa Core, 1.82 GHz Processor   
157      Snapdragon 695, Octa Core, 2.2 GHz Processor   
158    Snapdragon  8 Gen1, Octa Core, 3 GHz Processor   
159  Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor   
160      Snapdragon 680, Octa Core, 2.4 GHz Processor   

                           ram                                   battery  \
0    12 GB RAM, 256 GB inbuilt  5000 mAh Battery with 100W Fast Charging   
1     6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   
2      4 GB RAM, 64 GB inbuilt   5000 mAh Battery with 15W Fast Charging   
3     6 GB RAM, 128 GB inbuilt       5000 mAh Battery with Fast Charging   
4     6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 67W Fast Charging   
..                         ...                                       ...   
156    2 GB RAM, 32 GB inbuilt                          5000 mAh Battery   
157   8 GB RAM, 128 GB inbuilt   4500 mAh Battery with 33W Fast Charging   
158   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 65W Fast Charging   
159  12 GB RAM, 256 GB inbuilt   4520 mAh Battery with 67W Fast Charging   
160   6 GB RAM, 128 GB inbuilt   5000 mAh Battery with 33W Fast Charging   

                                               display  \
0    6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1    6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2    6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3    6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4    6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
..                                                 ...   
156  6.5 inches, 720 x 1600 px Display with Water D...   
157  6.43 inches, 1080 x 2400 px Display with Punch...   
158  6.4 inches, 1080 x 2400 px, 120 Hz Display wit...   
159  7.1 inches, 1792 x 1920 px, 120 Hz Display wit...   
160  6.4 inches, 1080 x 2400 px, 90 Hz Display with...   

                                                camera  \
0    50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1    64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2    50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...   
3    50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...   
4    108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...   
..                                                 ...   
156                      8 MP Rear & 5 MP Front Camera

In [701]:
temp_df = df1['card'].str.contains('Android',case=False,na=False)
temp_df

0       False
1       False
2       False
3       False
4       False
        ...  
1015     True
1016    False
1017    False
1018    False
1019    False
Name: card, Length: 982, dtype: bool

In [702]:
df1.loc[temp_df,'os'] = df1.loc[temp_df,'card'] 
df1.loc[temp_df,'card'] = 'Memory Card Not Supported'


In [703]:
df1['card'].value_counts()

card
Memory Card Not Supported                                             327
Memory Card Supported, upto 1 TB                                      171
Memory Card Supported, upto 512 GB                                    105
Memory Card (Hybrid), upto 1 TB                                        91
Memory Card Supported                                                  89
Memory Card Supported, upto 256 GB                                     89
Memory Card (Hybrid)                                                   31
Memory Card (Hybrid), upto 256 GB                                      15
Memory Card (Hybrid), upto 512 GB                                      11
Memory Card Supported, upto 128 GB                                      7
iOS v14                                                                 6
Memory Card Supported, upto 2 TB                                        5
Memory Card Supported, upto 32 GB                                       4
Memory Card (Hybrid), upto 2 TB  

In [704]:
temp_df = df1['card'].str.contains('iOS',case=False,na=False)

df1.loc[temp_df,'card'] ='Memory Card Not Supported'

In [705]:
df1['card'].value_counts()

card
Memory Card Not Supported                                             340
Memory Card Supported, upto 1 TB                                      171
Memory Card Supported, upto 512 GB                                    105
Memory Card (Hybrid), upto 1 TB                                        91
Memory Card Supported, upto 256 GB                                     89
Memory Card Supported                                                  89
Memory Card (Hybrid)                                                   31
Memory Card (Hybrid), upto 256 GB                                      15
Memory Card (Hybrid), upto 512 GB                                      11
Memory Card Supported, upto 128 GB                                      7
Memory Card Supported, upto 2 TB                                        5
Memory Card Supported, upto 32 GB                                       4
Memory Card (Hybrid), upto 128 GB                                       3
Memory Card (Hybrid), upto 64 GB 

In [706]:
temp_df = df1['card'].str.contains('camera',case=False,na=False)
df1.loc[temp_df,'card'] = 'Memory Card Not Supported' 

In [707]:
df1['card'].value_counts()

card
Memory Card Not Supported              352
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      89
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Memory Card Supported, upto 1000 GB      1
HarmonyOS v2.0                           1
HarmonyOS                                1
Name: count, dtype: int64

In [708]:
temp_df = df1['card'].str.contains('OS')

df1.loc[temp_df,'os']=df1.loc[temp_df,'card']
df1.loc[temp_df,'card'] = 'Memory Card Not Supported' 

In [709]:
# now let's see os

In [710]:
df1[df1['os'].str.contains('FM',case=False,na=False)]

index                         model   price  rating  \
111    113               Apple iPhone 12   51999    74.0   
149    151          Apple iPhone 12 Mini   40999    74.0   
307    309       Apple iPhone 12 (128GB)   55999    75.0   
363    365  Apple iPhone 12 Mini (128GB)   45999    75.0   
439    441        Apple iPhone SE 3 2022   43900     NaN   
448    450           Apple iPhone 15 Pro  130990    75.0   
607    609               Apple iPhone 7s   52990     NaN   
628    630   Apple iPhone 12 Pro (512GB)  139900    80.0   
656    658          Apple iPhone SE 2020   39900    63.0   
762    764             Apple iPhone SE 4   49990    60.0   
853    855   Apple iPhone 12 Pro (256GB)  119900    80.0   
913    915  Apple iPhone 12 Mini (256GB)   55999    75.0   
914    916       Apple iPhone 12 (256GB)   67999    76.0   

                                         sim  \
111  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
149  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
307  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
363  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
439  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
448  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
607         Single Sim, 3G, 4G, VoLTE, Wi-Fi   
628  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
656      Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC   
762  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
853  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
913  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
914  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                         processor                       ram  \
111       Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
149       Bionic A14, Hexa Core, 3.1 GHz Processor   4 GB RAM, 64 GB inbuilt   
307       Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
363       Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 128 GB inbuilt   
439     Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
448                                    Bionic  A16  8 GB RAM, 128 GB inbuilt   
607  Fusion APL1024, Quad Core, 2.37 GHz Processor   3 GB RAM, 32 GB inbuilt   
628       Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 512 GB inbuilt   
656      A13 Bionic, Hexa Core, 2.65 GHz Processor   3 GB RAM, 64 GB inbuilt   
762     Bionic  A15, Hexa Core, 3.22 GHz Processor             64 GB inbuilt   
853       Bionic A14, Hexa Core, 3.1 GHz Processor  6 GB RAM, 256 GB inbuilt   
913       Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   
914       Bionic A14, Hexa Core, 3.1 GHz Processor  4 GB RAM, 256 GB inbuilt   

                                     battery  \
111                                      NaN   
149                                      NaN   
307                                      NaN   
363                                      NaN   
439                                      NaN   
448                                      NaN   
607                         2230 mAh Battery   
628                                      NaN   
656  1821 mAh Battery with 18W Fast Charging   
762                                      NaN   
853                                      NaN   
913                                      NaN   
914                                      NaN   

                                               display  \
111       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
149       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
307       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
363       12 MP + 12 MP Dual Rear & 12 MP Front Camera   
439                     12 MP Rear & 7 MP Front Camera   
448  50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
607                  4.7 inches, 750 x 1334 px Display   
628  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
656                  4.7 inches, 750 x 1334 px Display   
762                  12 MP Rear & 10.8 MP Front Camera   
853  12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...   
9

In [711]:
temp_df = df1['camera'].str.contains('ios',case=False,na=False)


In [712]:
df1.loc[temp_df,'camera'] = df1.loc[temp_df,'display']
df1.loc[temp_df,'os'] = df1.loc[temp_df,'camera']
df1.loc[temp_df,'display'] = None

In [714]:
df1

index                            model  price  rating  \
0         2                    OnePlus 11 5G  54999    89.0   
1         3        OnePlus Nord CE 2 Lite 5G  19989    81.0   
2         4            Samsung Galaxy A14 5G  16499    75.0   
3         5             Motorola Moto G62 5G  14999    81.0   
4         6               Realme 10 Pro Plus  24999    82.0   
...     ...                              ...    ...     ...   
1015   1017       Motorola Moto Edge S30 Pro  34990    83.0   
1016   1018                      Honor X8 5G  14990    75.0   
1017   1019  POCO X4 GT 5G (8GB RAM + 256GB)  28990    85.0   
1018   1020             Motorola Moto G91 5G  19990    80.0   
1019   1021           Samsung Galaxy M52s 5G  24990    74.0   

                                                    sim  \
0               Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
2                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
3                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
4                    Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
...                                                 ...   
1015                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1016                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   
1017  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1018            Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
1019                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                            processor  \
0     Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor   
1        Snapdragon 695, Octa Core, 2.2 GHz Processor   
2           Exynos 1330, Octa Core, 2.4 GHz Processor   
3       Snapdragon  695, Octa Core, 2.2 GHz Processor   
4        Dimensity 1080, Octa Core, 2.6 GHz Processor   
...                                               ...   
1015    Snapdragon 8 Gen1, Octa Core, 3 GHz Processor   
1016   Snapdragon  480+, Octa Core, 2.2 GHz Processor   
1017    Dimensity 8100, Octa Core, 2.85 GHz Processor   
1018     Snapdragon 695, Octa Core, 2.2 GHz Processor   
1019                              Octa Core Processor   

                            ram                                    battery  \
0     12 GB RAM, 256 GB inbuilt   5000 mAh Battery with 100W Fast Charging   
1      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 33W Fast Charging   
2       4 GB RAM, 64 GB inbuilt    5000 mAh Battery with 15W Fast Charging   
3      6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
4      6 GB RAM, 128 GB inbuilt    5000 mAh Battery with 67W Fast Charging   
...                         ...                                        ...   
1015   8 GB RAM, 128 GB inbuilt  5000 mAh Battery with 68.2W Fast Charging   
1016   6 GB RAM, 128 GB inbuilt  5000 mAh Battery with 22.5W Fast Charging   
1017   8 GB RAM, 256 GB inbuilt    5080 mAh Battery with 67W Fast Charging   
1018   6 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   
1019   8 GB RAM, 128 GB inbuilt        5000 mAh Battery with Fast Charging   

                                                display  \
0     6.7 inches, 1440 x 3216 px, 120 Hz Display wit...   
1     6.59 inches, 1080 x 2412 px, 120 Hz Display wi...   
2     6.6 inches, 1080 x 2408 px, 90 Hz Display with...   
3     6.55 inches, 1080 x 2400 px, 120 Hz Display wi...   
4     6.7 inches, 1080 x 2412 px, 120 Hz Display wit...   
...                                                 ...   
1015  6.67 inches, 1080 x 2460 px, 120 Hz Display wi...   
1016  6.5 inches, 720 x 1600 px Display with Water D...   
1017  6.6 inches, 1080 x 2460 px, 144 Hz Display wit...   
1018  6.8 inches, 1080 x 2400 px Display with Punch ...   
1019  6.5 inches, 1080 x 2400 px Display with Water ...   

                                                 camera  \
0     50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...   
1     64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...   
2     50 MP + 2 MP + 2 MP Triple

In [728]:
temp_df = df1['os'].str.contains('Camera',case=False,na=False)
df1.loc[temp_df,'os'] = None



Empty DataFrame
Columns: [index, model, price, rating, sim, processor, ram, battery, display, camera, card, os]
Index: []

In [734]:
temp_df = df1[df1['os'].str.contains('Camera')]
temp_df

ValueError: Cannot mask with non-boolean array containing NA / NaN values